version: '3'
services:
  node01:
    env_file:
      - ./env/server.env
    image: mysql/mysql-server:latest
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  node02:
    env_file:
      - ./env/server.env
    image: mysql/mysql-server:latest
    ports:
      - "3302:3306"
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  node03:
    env_file:
      - ./env/server.env
    image: mysql/mysql-server:latest
    ports:
      - "3303:3306"
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  shell:
    env_file:
      - ./env/shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./js/:/scripts/
        - ./dump/:/dump/
    depends_on:
      - node01
      - node02
      - node03

  router:
    env_file:
      - ./env/router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    depends_on:
      - node01
      - node02
      - node03
      - shell
    restart: on-failure