version: '3.7'
services:
  node01: &nodes
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - "3301:3306"
      - "33061:33060"
    command: ["mysqld",
    "--server_id=1",
    "--binlog_checksum=NONE",
    "--gtid_mode=ON",
    "--enforce_gtid_consistency=ON",
    "--log_bin",
    "--log_slave_updates=ON",
    "--master_info_repository=TABLE",
    "--relay_log_info_repository=TABLE",
    "--transaction_write_set_extraction=XXHASH64",
    "--user=mysql",
    "--skip-host-cache",
    "--skip-name-resolve",
    "--default_authentication_plugin=mysql_native_password"]
  node02:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - "3302:3306"
      - "33062:33060"
    command: ["mysqld",
    "--server_id=2",
    "--binlog_checksum=NONE",
    "--gtid_mode=ON",
    "--enforce_gtid_consistency=ON",
    "--log_bin",
    "--log_slave_updates=ON",
    "--master_info_repository=TABLE",
    "--relay_log_info_repository=TABLE",
    "--transaction_write_set_extraction=XXHASH64",
    "--user=mysql",
    "--skip-host-cache",
    "--skip-name-resolve",
    "--default_authentication_plugin=mysql_native_password"]
  node03:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - "3303:3306"
      - "33063:33060"
    command: ["mysqld",
    "--server_id=3",
    "--binlog_checksum=NONE",
    "--gtid_mode=ON",
    "--enforce_gtid_consistency=ON",
    "--log_bin",
    "--log_slave_updates=ON",
    "--master_info_repository=TABLE",
    "--relay_log_info_repository=TABLE",
    "--transaction_write_set_extraction=XXHASH64",
    "--user=mysql",
    "--skip-host-cache",
    "--skip-name-resolve",
    "--default_authentication_plugin=mysql_native_password"]
  
  shell:
    image: mysql/mysql-server:latest
    entrypoint: "/bin/shell-entrypoint"
    environment: &other-environment
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_INNODB_NUM_MEMBERS
      - MYSQLSH_SCRIPT
      - MYSQL_SCRIPT
    volumes:
        - "./shell-entrypoint.sh:/bin/shell-entrypoint"
        - "./js/cluster-setup.js:/tmp/cluster-setup.js"
        - "./dump/:/tmp/dump/"
    depends_on: &node-depends
      - node01
      - node02
      - node03

  router:
    image: mysql/mysql-router:latest
    env_file:
      router.env
    ports:
      - "6446:6446"
      - "6447:6447"
    depends_on: *node-depends
    restart: always