---
# defaults file for conf_audit_client

audit_remote_server: ns.otus.test
audit_remote_server_port: 60
audit_rules:
  - '-w /var/log/audit/ -k auditlog'
  - '-w /etc/audit/ -p wa -k auditconfig'
  - '-w /etc/libaudit.conf -p wa -k auditconfig'
  - '-w /etc/audisp/ -p wa -k audispconfig'
  - '-w /sbin/auditctl -p x -k audittools'
  - '-w /sbin/auditd -p x -k audittools'
  - '-a exit,always -F arch=b64 -S execve'
  - '-a exit,always -F arch=b32 -S execve'
audit_domain: otus.test
...