---
# defaults file for add_repos

repo:
  - { name: 'epel', key: 'https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7', url: 'https://download.fedoraproject.org/pub/epel/$releasever/$basearch/', file: '/etc/yum.repos.d/epel.repo'}
  - { name: 'elrepo', key: 'https://www.elrepo.org/RPM-GPG-KEY-elrepo.org', url: 'https://elrepo.org/linux/elrepo/el7/x86_64/', file: '/etc/yum.repos.d/elrepo.repo'}
  - { name: 'elrepo-kernel', key: 'https://www.elrepo.org/RPM-GPG-KEY-elrepo.org', url: 'https://elrepo.org/linux/kernel/el7/x86_64/', file: '/etc/yum.repos.d/epel.repo'}
...