---
#
# Setup a vagrant host
#

- name: Setup new host
  hosts: node1.homework.local
  become: yes

  roles:
  - { role: add_repos }
  - { role: deploy_monitoring_tools }
  - { role: setup_atop_service }
  - { role: tune_kernel }
  - { role: upgrade_kernel }
...