---
# tasks file for add_bacula

# Add bacula packages

- name: Install bacula server packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ bacula_packages }}"

# Create bacula database

- name: Check if bacula databbase exists
  become_user: postgres
  action: command
    psql -qAt -c "SELECT datname FROM pg_database"
  register: db_bacula_present

- name: Create bacula database if not exists
  become_user: postgres
  action: command
    /usr/libexec/bacula/create_postgresql_database
  when: db_bacula_present.stdout.find('bacula') == -1

- name: Check tables in bacula database
  become_user: postgres
  command:
    psql -d bacula -qAt -c "select table_name from information_schema.tables where table_schema = 'public'"
  register: db_bacula_tables_present

- name: Create bacula DB tables
  become_user: postgres
  action: command
    /usr/libexec/bacula/make_postgresql_tables
  when: db_bacula_tables_present.stdout.find('pathvisibility') == -1

- name: Check privileges in bacula DB
  become_user: postgres
  action: command
    psql -d bacula -qAt -c "SELECT grantee FROM information_schema.role_table_grants where table_name='pathvisibility'"
  register: db_bacula_priv_present

- name: Grant bacula priveleges
  become_user: postgres
  action: command
    /usr/libexec/bacula/grant_postgresql_privileges
  when: db_bacula_priv_present.stdout.find('bacula') == -1

# Set Bacula db password

- name: Add bacula pg_user password
  become: yes
  become_user: postgres
  postgresql_user:
    db: bacula
    name: bacula
    password: "{{ PG_BACULA_PASSWORD }}"

# Create Bacula folders, check SELinux permissions

- name: Check bacula folders
  stat:
    path: "{{ item }}"
  register: folder_stats
  with_items: "{{ bacula_folders }}"

- name: Create bacula folders
  file:
    path: "{{ item }}"
    state: directory
    owner: bacula
    group: bacula
    mode: 0755
  when: item.stat.exists == false
  with_items: "{{ folder_stats.results }}"

- name: SElinux fix permissions for bacula folders
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: bacula_store_t
    state: present
  with_items: "{{ bacula_folders }}"

- name: Apply new SELinux file context to filesystem
  action: command
    restorecon -irv {{ item }}
  with_items: "{{ bacula_folders }}"

# Add configuration files

- name: Add .pgpass file
  template:
    src: pgpass.j2
    dest: /var/spool/bacula/.pgpass
    owner: bacula
    group: bacula
    mode: 0600

- name: Add .conf files
  template:
    src: "{{ item }}.j2"
    dest: /etc/bacula/{{ item }}
    owner: bacula
    group: bacula
    mode: 0600
  with_items: "{{ conf_files }}"
  notify: Restart bacula

# Enable and start Bacula services

- name: Enable Bacula services
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items: "{{ bacula_services }}"

- name: Start Bacula services
  systemd:
    name: "{{ item }}"
    state: started
  with_items: "{{ bacula_services }}"
...
