---
# tasks file for add_pgsql11

- name: PostgreSQL 11 server install
  yum:
    name: 
      - postgresql11-server
      - postgresql11
      - python-psycopg2
    state: latest

- name: Set postgresql as a service
  systemd:
    name: postgresql-11
    enabled: yes
    masked: no

- name: Check if postgres database dir exsits
  stat:
    path: /var/lib/pgsql/11/initdb.log
  register: pg_data_exist

- name: Postgres init database
  action: command
    /usr/pgsql-11/bin/postgresql-11-setup
    initdb
  when: pg_data_exist.stat.exists == False 

- name: Add pg_hba.conf to data directory
  template: 
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/11/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644

- name: Start PostgreSQL server
  systemd:
    name: postgresql-11
    state: started
...
