---
# tasks file for kerberos-client
- name: install kerberos client packages
  yum:
    name: ['krb5-workstation','pam_krb5']
    state: present

- name: copy config files
  copy:
    src: krb.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: create a principal entires on client
  shell: kadmin -p {{ kadmin_user }} -w {{ kadmin_pass }} -q "addprinc -randkey  -kvno 3 {{ item }}"
  with_items:
   - host/client.otus.test@OTUS.TEST
   - nfs/client.otus.test@OTUS.TEST
   - cifs/client.otus.test@OTUS.TEST

- name: add entires to keytab on client
  shell: kadmin -p {{ kadmin_user }} -w {{ kadmin_pass }} -q "ktadd {{ item }}"
  with_items:
   - host/client.otus.test
   - nfs/client.otus.test
   - cifs/client.otus.test

- name: obtain kerberos ticket for root
  shell: echo "{{ kadmin_pass }}" | kinit -p {{ kadmin_user }}

- name: enable pam kerberos auth
  shell: authconfig --enablekrb5 --update
...