---
# tasks file for add_pgsql11
- name: install postgres reposiroty from url
  yum:
    name: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm

- name: PostgreSQL 11 server install
  yum:
    name: 
      - postgresql11-server
      - postgresql11
      - python-psycopg2
    state: latest

- name: Set postgresql as a service
  systemd:
    name: postgresql-11
    enabled: yes
    masked: no

- name: Check if postgres database dir exsits
  stat:
    path: /var/lib/pgsql/11/initdb.log
  register: pg_data_exist

- name: Postgres init database
  action: command
    /usr/pgsql-11/bin/postgresql-11-setup
    initdb  
  when: pg_data_exist.stat.exists == False

- name: Start PostgreSQL server
  systemd:
    name: postgresql-11
    state: started

- name: Add replica user
  become_user: postgres  
  command: psql -c "CREATE USER replication REPLICATION LOGIN CONNECTION LIMIT 5 ENCRYPTED PASSWORD 'swimming3';"

- name: Add replica connections
  become_user: postgres  
  command: psql -c "ALTER ROLE replication CONNECTION LIMIT 2;"

- name: Add pg_hba.conf to primary data directory
  template: 
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/11/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0700

- name: Add postgres.conf to primary data directory
  template: 
    src: postgresql.primary.conf.j2
    dest: /var/lib/pgsql/11/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0700

- name: Create archive dir
  file: 
    path: /var/lib/pgsql/11/archive
    state: directory
    group: postgres
    owner: postgres
    mode: 0700
  notify: Restart postgres
...
