---
# tasks file for add_grafana

- name: Install grafana
  yum:
    name: https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm
    state: present

- name: Install grafana
  yum:
    name: grafana
    state: latest

- name: Configuration file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Enable grafana service
  systemd:
    name: grafana-server
    enabled: yes
    masked: no
    state: started

- name: Start grafana service
  systemd:
    name: grafana-server
...
