---
# defaults file for deploy_ipa_server
ansible_user: kakoka
ansible_ssh_private_key_file: /Users/kakoka/.ssh/id_rsa
ipa_domain: homework.local
ipa_realm: HOMEWORK.LOCAL
ipa_pkg:
  - ipa-server
  - ipa-server-dns
  - bind-dyndb-ldap
ipa_install_command: ipa-server-install -U
ipa_add_rule_command: ipa sudorule-add 
ipa_grant_admin_command: ipa sudorule-add-user
ipa_user_add: ipa user-add
ipa_add_to_group: ipa group-add-member
...