---
- name: Transfer OpenVPN cert from server to client 
  hosts: all
  become: yes
  vars:
    temporary_local_path: /tmp
    project_local_path: /home/kakoka/git/otus-homework/hw20/ca
  tasks:
    - name: make temp dir
      file:
        path: "{{ temporary_local_path }}"
        state: directory
      delegate_to: 127.0.0.1
    - fetch:
        become: yes
        src: /etc/openvpn/server/client.conf
        dest: "{{ temporary_local_path }}/client.conf"
        flat: yes
    - name: client.conf file copy to project dir
      local_action: command cp "{{ temporary_local_path }}/client.conf" "{{ project_local_path }}"
...
