---
- name: config timescaledb.repo
  copy: 
    src: timescale_timescaledb.repo
    dest: /etc/yum.repos.d/timescale_timescaledb.repo
    owner: root
    group: root
    mode: 0644

- name: timescaledb install
  yum:
    name: timescaledb-postgresql-11
    state: present

- name: copy bin files
  copy:
    src: pg_prometheus.tar.gz
    dest: /tmp

- name: extract bin files
  shell:
    cmd: tar -zxvf pg_prometheus.tar.gz
    chdir: /tmp

- name: install pg_prometheus
  shell: 
    cmd: ./install.sh
    chdir: /tmp/pg_prometheus

# CREATE DATABASE monitoring;
# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
# CREATE EXTENSION IF NOT EXISTS pg_prometheus CASCADE;
...